# Docker Compose for development
# Simplified setup for local development with hot reloading

version: '3.8'

services:
  # Development Next.js application with hot reloading
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env.local
    depends_on:
      - redis
    networks:
      - aiass-dev
    restart: unless-stopped

  # Redis for development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - aiass-dev
    restart: unless-stopped

  # n8n for development
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Berlin
    volumes:
      - n8n_dev_data:/home/node/.n8n
    networks:
      - aiass-dev
    restart: unless-stopped

volumes:
  n8n_dev_data:

networks:
  aiass-dev:
    driver: bridge