apiVersion: v1
kind: ConfigMap
metadata:
  name: roomicor-config
  namespace: roomicor
  labels:
    app.kubernetes.io/name: roomicor
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_TELEMETRY_DISABLED: "1"
  # Add non-sensitive configuration here
  HEALTH_CHECK_ENDPOINT: "/api/health"
  LOG_LEVEL: "info"
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roomicor-config
  namespace: roomicor-staging
  labels:
    app.kubernetes.io/name: roomicor
    app.kubernetes.io/component: config
    environment: staging
data:
  NODE_ENV: "staging"
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_TELEMETRY_DISABLED: "1"
  HEALTH_CHECK_ENDPOINT: "/api/health"
  LOG_LEVEL: "debug"
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"