apiVersion: v1
kind: ServiceMonitor
metadata:
  name: roomicor-metrics
  namespace: roomicor
  labels:
    app.kubernetes.io/name: roomicor
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: roomicor
      app.kubernetes.io/component: service
  endpoints:
  - port: metrics
    path: /api/metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: roomicor-metrics
  namespace: roomicor
  labels:
    app.kubernetes.io/name: roomicor
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: roomicor
      app.kubernetes.io/component: service
  endpoints:
  - port: metrics
    path: /api/metrics
    interval: 30s
    scrapeTimeout: 10s
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'go_.*'
      action: drop

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: roomicor-alerts
  namespace: roomicor
  labels:
    app.kubernetes.io/name: roomicor
    app.kubernetes.io/component: monitoring
spec:
  groups:
  - name: roomicor.rules
    rules:
    # Application Health
    - alert: RoomicorAppDown
      expr: up{job="roomicor-service"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Roomicor application is down"
        description: "Roomicor application has been down for more than 1 minute."
    
    # High Error Rate
    - alert: RoomicorHighErrorRate
      expr: rate(http_requests_total{job="roomicor-service",status=~"5.."}[5m]) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value }} errors per second."
    
    # High Response Time
    - alert: RoomicorHighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="roomicor-service"}[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is {{ $value }}s."
    
    # High CPU Usage
    - alert: RoomicorHighCPU
      expr: rate(container_cpu_usage_seconds_total{pod=~"roomicor-app-.*"}[5m]) > 0.8
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage"
        description: "CPU usage is {{ $value }}%."
    
    # High Memory Usage
    - alert: RoomicorHighMemory
      expr: container_memory_usage_bytes{pod=~"roomicor-app-.*"} / container_spec_memory_limit_bytes > 0.9
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "High memory usage"
        description: "Memory usage is {{ $value }}%."
    
    # Pod Restart Frequency
    - alert: RoomicorPodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{pod=~"roomicor-app-.*"}[5m]) > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod is crash looping"
        description: "Pod {{ $labels.pod }} has restarted {{ $value }} times in the last 5 minutes."
    
    # Database Connection
    - alert: RoomicorDatabaseConnectionFailed
      expr: roomicor_database_connection_status == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Database connection failed"
        description: "Cannot connect to the database."
    
    # External Services
    - alert: RoomicorExternalServiceDown
      expr: roomicor_external_service_status{service=~"stripe|clerk|supabase"} == 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "External service is down"
        description: "External service {{ $labels.service }} is not responding."

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: roomicor
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
data:
  roomicor-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Roomicor Application Dashboard",
        "tags": ["roomicor"],
        "style": "dark",
        "timezone": "browser",
        "editable": true,
        "hideControls": false,
        "graphTooltip": 1,
        "panels": [
          {
            "id": 1,
            "title": "Request Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{job=\"roomicor-service\"}[5m])",
                "legendFormat": "{{method}} {{status}}"
              }
            ],
            "yAxes": [
              {
                "label": "Requests/sec"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
          },
          {
            "id": 2,
            "title": "Response Time",
            "type": "graph",
            "targets": [
              {
                "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job=\"roomicor-service\"}[5m]))",
                "legendFormat": "95th percentile"
              },
              {
                "expr": "histogram_quantile(0.50, rate(http_request_duration_seconds_bucket{job=\"roomicor-service\"}[5m]))",
                "legendFormat": "50th percentile"
              }
            ],
            "yAxes": [
              {
                "label": "Seconds"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
          },
          {
            "id": 3,
            "title": "Error Rate",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(http_requests_total{job=\"roomicor-service\",status=~\"5..\"}[5m])",
                "legendFormat": "5xx errors"
              },
              {
                "expr": "rate(http_requests_total{job=\"roomicor-service\",status=~\"4..\"}[5m])",
                "legendFormat": "4xx errors"
              }
            ],
            "yAxes": [
              {
                "label": "Errors/sec"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
          },
          {
            "id": 4,
            "title": "CPU Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{pod=~\"roomicor-app-.*\"}[5m])",
                "legendFormat": "{{pod}}"
              }
            ],
            "yAxes": [
              {
                "label": "CPU cores"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
          },
          {
            "id": 5,
            "title": "Memory Usage",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_usage_bytes{pod=~\"roomicor-app-.*\"}",
                "legendFormat": "{{pod}}"
              }
            ],
            "yAxes": [
              {
                "label": "Bytes"
              }
            ],
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 16}
          },
          {
            "id": 6,
            "title": "Pod Count",
            "type": "singlestat",
            "targets": [
              {
                "expr": "count(up{job=\"roomicor-service\"} == 1)",
                "legendFormat": "Healthy Pods"
              }
            ],
            "valueName": "current",
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 16}
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "refresh": "30s"
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: roomicor
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "/etc/prometheus/rules/*.yml"
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'roomicor-service'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - roomicor
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: roomicor-service
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
      
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name