# IMPORTANT: This is a template file. Do NOT commit actual secrets to git.
# Use `kubectl create secret` or external secret management tools.

apiVersion: v1
kind: Secret
metadata:
  name: roomicor-secrets
  namespace: roomicor
  labels:
    app.kubernetes.io/name: roomicor
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Authentication
  CLERK_SECRET_KEY: "YOUR_CLERK_SECRET_KEY"
  CLERK_WEBHOOK_SECRET: "YOUR_CLERK_WEBHOOK_SECRET"
  
  # Database
  SUPABASE_SERVICE_ROLE_KEY: "YOUR_SUPABASE_SERVICE_ROLE_KEY"
  DATABASE_URL: "postgresql://username:password@host:port/database"
  
  # Payments
  STRIPE_SECRET_KEY: "YOUR_STRIPE_SECRET_KEY"
  STRIPE_WEBHOOK_SECRET: "YOUR_STRIPE_WEBHOOK_SECRET"
  
  # AI Services
  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY"
  MCP_API_KEY: "YOUR_MCP_API_KEY"
  AGUI_API_KEY: "YOUR_AGUI_API_KEY"
  
  # Automation
  N8N_API_KEY: "YOUR_N8N_API_KEY"
  N8N_WEBHOOK_URL: "YOUR_N8N_WEBHOOK_URL"
  MAKE_WEBHOOK_TOKEN: "YOUR_MAKE_WEBHOOK_TOKEN"
  MAKE_WEBHOOK_SECRET: "YOUR_MAKE_WEBHOOK_SECRET"
  
  # CMS
  WORDPRESS_API_URL: "YOUR_WORDPRESS_API_URL"
  WORDPRESS_USERNAME: "YOUR_WORDPRESS_USERNAME"
  WORDPRESS_PASSWORD: "YOUR_WORDPRESS_PASSWORD"
  
  # Cache
  REDIS_URL: "redis://redis-service:6379"
  REDIS_PASSWORD: "YOUR_REDIS_PASSWORD"

---
apiVersion: v1
kind: Secret
metadata:
  name: roomicor-secrets
  namespace: roomicor-staging
  labels:
    app.kubernetes.io/name: roomicor
    app.kubernetes.io/component: secrets
    environment: staging
type: Opaque
stringData:
  # Use staging/test credentials
  CLERK_SECRET_KEY: "YOUR_STAGING_CLERK_SECRET_KEY"
  CLERK_WEBHOOK_SECRET: "YOUR_STAGING_CLERK_WEBHOOK_SECRET"
  SUPABASE_SERVICE_ROLE_KEY: "YOUR_STAGING_SUPABASE_SERVICE_ROLE_KEY"
  DATABASE_URL: "postgresql://username:password@staging-host:port/staging-database"
  STRIPE_SECRET_KEY: "sk_test_YOUR_STRIPE_TEST_KEY"
  STRIPE_WEBHOOK_SECRET: "YOUR_STAGING_STRIPE_WEBHOOK_SECRET"
  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY"
  MCP_API_KEY: "YOUR_STAGING_MCP_API_KEY"
  AGUI_API_KEY: "YOUR_STAGING_AGUI_API_KEY"
  N8N_API_KEY: "YOUR_STAGING_N8N_API_KEY"
  N8N_WEBHOOK_URL: "YOUR_STAGING_N8N_WEBHOOK_URL"
  MAKE_WEBHOOK_TOKEN: "YOUR_STAGING_MAKE_WEBHOOK_TOKEN"
  MAKE_WEBHOOK_SECRET: "YOUR_STAGING_MAKE_WEBHOOK_SECRET"
  WORDPRESS_API_URL: "YOUR_STAGING_WORDPRESS_API_URL"
  WORDPRESS_USERNAME: "YOUR_STAGING_WORDPRESS_USERNAME"
  WORDPRESS_PASSWORD: "YOUR_STAGING_WORDPRESS_PASSWORD"
  REDIS_URL: "redis://redis-service:6379"
  REDIS_PASSWORD: "YOUR_STAGING_REDIS_PASSWORD"